### ISSUE TITLE
[BE] 로그인 시 405 에러 (Method Not Allowed) ⚠️

### ISSUE THREAD

**Issue by WiseJade** [codestates-seb/seb39_main_059#153]
<img width="1061" alt="로그인 에러" src="https://user-images.githubusercontent.com/104193237/193013836-26e26ed0-af2d-45c9-a40c-dea80b4008ca.png">

POST 요청으로 로그인 요청 보낼 시 405 에러 뜨고 위 사진과 같이 GET 요청은 support 하지 않는다는 에러가 납니다.

**Comment by InjaeYu** [comment]
확인 결과 SecurityConfig에서 `formLogin.loginProcessingUrl(...)` 로직을 제거해야 정상적으로 동작 됨을 확인하였습니다.

해당 에러가 발생하는 이유에 대한 추측으로는 Security에서 제공되는 로그인 방식이 아닌 Token을 사용한 로그인 방식을 구현하여 제공하는 것이기 때문에 Security에서 제공되는 로그인 기능과 중복 적용 되며 문제가 발생한 것으로 추측됩니다.
