### ISSUE TITLE
[BE] 고양이 등록 시 성별 유효성 검사 에러

### ISSUE THREAD

**Issue by InjaeYu** [codestates-seb/seb39_main_059#155]
고양이 등록 시 성별 유효성 검사에 맞는 데이터를 입력하였으나 유효성 에러 발생

입력한 데이터
`{
    "name": "군밤",
    "birthYear": 2020,
    "birthMonth": 7,
    "birthDay": 9,
    "breed": "포메라니안",
    "sex": "m",
    "weight": 5,
    "image": "image",
    "body": "군밤이는 귀엽다 짱짱 귀엽다 군밤이는 고양이가 아니고 강아지인데 왜 고양이처럼 행동을 하는 것일까? 군밤이는 고양이처럼 식빵을 굽는다. 그래서 군밤식빵이다?"
}`

발생한 유효성 에러
`
Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument
...
Field error in object 'catPostDto' on field 'sex': rejected value [m]
...
default message ["\^[mf]\$"와 일치해야 합니다]] ]
`

**Comment by WiseJade** [comment]
Pattern 애너테이션 안에 정규식 `^[mf]$` 이렇게 쓰면 해결됩니다! 고양이 등록하기 기능에 다른 오류도 발견하여 같이 반영하여 PR하겠습니다! 😄
