### ISSUE TITLE
[BE] 복합 PK 사용시 타입 매핑 안되는 오류 ⚠️

### ISSUE THREAD

**Issue by WiseJade** [codestates-seb/seb39_main_059#159]
N:N (다대다) 관계에 있는 엔티티끼리 연관관계 매핑을 하기 위해서 1:N , 1:N으로 나눠서 중간에 엔티티를 하나 더 추가하였습니다.
이렇게 중간에 추가된 엔티티는 별도의 Id(PK) 값을 가지지 않고 FK 만 2개 가지고 있어 두개의 FK를 묶어서 PK로 사용하였는데 요청 시 엔티티들(TagTo~)에서 오류가 발생하여 확인해봤더니 타입이 매핑이 안됩니다!

PK 두개를 spring에서 ID 를 두개 사용하다보면 오류가 발생하여 Serializable로 묶어서 사용하였습니다.
여기서 코드상으로는 PK가 모두 엔티티(클래스)로 되어 있습니다. 그래서 ID를 묶어주는 클래스에서도 동일하게 엔티티로 필드값을 넣었으나 실제로 DB에 저장될 때는 엔티티의 Id를 가지고 와서 PK로 저장하기 때문에 오류가 발생하는 것으로 보입니다.

`public class TagToCatId implements Serializable {
    private Long catTag;
    private Long cat;
}`

코드를 이렇게 변경하여 요청 보냈을 때는 문제없이 저장되었습니다!

**Comment by InjaeYu** [comment]
확인하였습니다!
